// Generated by scripts/generate-stunt-sites.ts. Do not edit by hand; re-run `npm run generate:stunts`.
import type { StuntSite } from './stuntSites';

export const STUNT_SITES: StuntSite[] = [
  {
    "id": "river-jump-malakkappara-river-2-28",
    "label": "Chalakkudy River Jump",
    "kind": "river",
    "ramps": [
      {
        "model": "wedge",
        "entry": [
          -683.307,
          79.597,
          -648.962
        ],
        "yaw": 1.759
      },
      {
        "model": "wedge",
        "entry": [
          -646.214,
          79.599,
          -656.027
        ],
        "yaw": -1.383
      }
    ],
    "sign": {
      "position": [
        -690.231,
        76.782,
        -642.553
      ],
      "yaw": -1.383
    },
    "start": {
      "position": [
        -710.813,
        74.88,
        -643.723
      ],
      "headingRad": 1.383
    },
    "clear": [
      {
        "x": -683.307,
        "z": -648.962,
        "radius": 10
      },
      {
        "x": -646.214,
        "z": -656.027,
        "radius": 10
      },
      {
        "x": -678.514,
        "z": -649.875,
        "radius": 10
      },
      {
        "x": -651.008,
        "z": -655.114,
        "radius": 10
      },
      {
        "x": -698.042,
        "z": -646.155,
        "radius": 10
      },
      {
        "x": -631.479,
        "z": -658.834,
        "radius": 10
      }
    ]
  },
  {
    "id": "river-jump-malakkappara-river-3-64",
    "label": "Chalakkudy River Jump II",
    "kind": "river",
    "ramps": [
      {
        "model": "wedge",
        "entry": [
          -658.626,
          73.837,
          -508.833
        ],
        "yaw": 1.728
      },
      {
        "model": "wedge",
        "entry": [
          -621.332,
          73.794,
          -514.746
        ],
        "yaw": -1.414
      }
    ],
    "sign": {
      "position": [
        -665.744,
        75.963,
        -502.642
      ],
      "yaw": -1.414
    },
    "start": {
      "position": [
        -686.281,
        75.848,
        -504.449
      ],
      "headingRad": 1.414
    },
    "clear": [
      {
        "x": -658.626,
        "z": -508.833,
        "radius": 10
      },
      {
        "x": -621.332,
        "z": -514.746,
        "radius": 10
      },
      {
        "x": -653.806,
        "z": -509.597,
        "radius": 10
      },
      {
        "x": -626.152,
        "z": -513.982,
        "radius": 10
      },
      {
        "x": -673.441,
        "z": -506.484,
        "radius": 10
      },
      {
        "x": -606.517,
        "z": -517.094,
        "radius": 10
      }
    ]
  },
  {
    "id": "stunt-park-kodassery-1",
    "label": "Kodassery Stunt Park",
    "kind": "park",
    "ramps": [
      {
        "model": "kicker",
        "entry": [
          -776.828,
          46.955,
          -355.129
        ],
        "yaw": 1.7
      },
      {
        "model": "wedge",
        "entry": [
          -766.867,
          46.953,
          -371.555
        ],
        "yaw": 1.7
      },
      {
        "model": "wedge",
        "entry": [
          -743.307,
          47.143,
          -374.626
        ],
        "yaw": -1.441
      },
      {
        "model": "curve",
        "entry": [
          -763.935,
          46.954,
          -380.005
        ],
        "yaw": 1.7
      }
    ],
    "sign": {
      "position": [
        -787.778,
        47.535,
        -361.769
      ],
      "yaw": -1.441
    },
    "start": {
      "position": [
        -798.643,
        48.029,
        -352.285
      ],
      "headingRad": 1.441
    },
    "clear": [
      {
        "x": -754.063,
        "z": -366.165,
        "radius": 46
      }
    ]
  },
  {
    "id": "stunt-park-chokkana-1",
    "label": "Chokkana Stunt Park",
    "kind": "park",
    "ramps": [
      {
        "model": "kicker",
        "entry": [
          -263.599,
          67.273,
          -334.031
        ],
        "yaw": 1.459
      },
      {
        "model": "wedge",
        "entry": [
          -250.001,
          66.719,
          -347.598
        ],
        "yaw": 1.459
      },
      {
        "model": "wedge",
        "entry": [
          -226.389,
          66.33,
          -344.947
        ],
        "yaw": -1.683
      },
      {
        "model": "curve",
        "entry": [
          -245.133,
          66.359,
          -355.102
        ],
        "yaw": 1.459
      }
    ],
    "sign": {
      "position": [
        -272.644,
        67.06,
        -343.096
      ],
      "yaw": -1.683
    },
    "start": {
      "position": [
        -285.462,
        67.121,
        -336.485
      ],
      "headingRad": 1.683
    },
    "clear": [
      {
        "x": -238.857,
        "z": -339.303,
        "radius": 46
      }
    ]
  },
  {
    "id": "stunt-park-chokkana-2",
    "label": "Chokkana Stunt Park II",
    "kind": "park",
    "ramps": [
      {
        "model": "kicker",
        "entry": [
          -414.947,
          62.088,
          -633.904
        ],
        "yaw": -0.878
      },
      {
        "model": "wedge",
        "entry": [
          -414.605,
          63.075,
          -614.698
        ],
        "yaw": -0.878
      },
      {
        "model": "wedge",
        "entry": [
          -432.892,
          63.368,
          -599.528
        ],
        "yaw": 2.263
      },
      {
        "model": "curve",
        "entry": [
          -412.576,
          63.67,
          -605.987
        ],
        "yaw": -0.878
      }
    ],
    "sign": {
      "position": [
        -402.143,
        63.024,
        -634.132
      ],
      "yaw": 2.263
    },
    "start": {
      "position": [
        -398.015,
        62.891,
        -647.951
      ],
      "headingRad": -2.263
    },
    "clear": [
      {
        "x": -428.31,
        "z": -612.424,
        "radius": 46
      }
    ]
  },
  {
    "id": "stunt-park-kurumali-1",
    "label": "Kurumali Stunt Park",
    "kind": "park",
    "ramps": [
      {
        "model": "kicker",
        "entry": [
          -681.428,
          39.66,
          -57.899
        ],
        "yaw": 1.6
      },
      {
        "model": "wedge",
        "entry": [
          -669.868,
          41.597,
          -73.24
        ],
        "yaw": 1.6
      },
      {
        "model": "wedge",
        "entry": [
          -646.118,
          41.639,
          -73.929
        ],
        "yaw": -1.542
      },
      {
        "model": "curve",
        "entry": [
          -666.102,
          42.641,
          -81.353
        ],
        "yaw": 1.6
      }
    ],
    "sign": {
      "position": [
        -691.656,
        41.119,
        -65.606
      ],
      "yaw": -1.542
    },
    "start": {
      "position": [
        -703.419,
        40.223,
        -57.261
      ],
      "headingRad": 1.542
    },
    "clear": [
      {
        "x": -657.67,
        "z": -66.591,
        "radius": 46
      }
    ]
  },
  {
    "id": "stunt-park-kodassery-2",
    "label": "Kodassery Stunt Park II",
    "kind": "park",
    "ramps": [
      {
        "model": "kicker",
        "entry": [
          61.527,
          72.467,
          -856.054
        ],
        "yaw": -1.832
      },
      {
        "model": "wedge",
        "entry": [
          46.06,
          74.063,
          -844.661
        ],
        "yaw": -1.832
      },
      {
        "model": "wedge",
        "entry": [
          23.106,
          73.905,
          -850.797
        ],
        "yaw": 1.31
      },
      {
        "model": "curve",
        "entry": [
          40.13,
          75.005,
          -837.966
        ],
        "yaw": -1.832
      }
    ],
    "sign": {
      "position": [
        69.122,
        73.693,
        -845.743
      ],
      "yaw": 1.31
    },
    "start": {
      "position": [
        82.781,
        73.076,
        -850.372
      ],
      "headingRad": -1.31
    },
    "clear": [
      {
        "x": 36.275,
        "z": -854.523,
        "radius": 46
      }
    ]
  },
  {
    "id": "stunt-park-kodaly-1",
    "label": "Kodaly Stunt Park",
    "kind": "park",
    "ramps": [
      {
        "model": "kicker",
        "entry": [
          -456.251,
          26.608,
          68.323
        ],
        "yaw": 1.446
      },
      {
        "model": "wedge",
        "entry": [
          -442.475,
          28.905,
          54.934
        ],
        "yaw": 1.446
      },
      {
        "model": "wedge",
        "entry": [
          -418.9,
          28.763,
          57.894
        ],
        "yaw": -1.696
      },
      {
        "model": "curve",
        "entry": [
          -437.51,
          29.889,
          47.495
        ],
        "yaw": 1.446
      }
    ],
    "sign": {
      "position": [
        -465.176,
        28.471,
        59.139
      ],
      "yaw": -1.696
    },
    "start": {
      "position": [
        -478.079,
        27.509,
        65.582
      ],
      "headingRad": 1.696
    },
    "clear": [
      {
        "x": -431.441,
        "z": 63.375,
        "radius": 46
      }
    ]
  },
  {
    "id": "stunt-park-kadambode-1",
    "label": "Kadambode Stunt Park",
    "kind": "park",
    "ramps": [
      {
        "model": "kicker",
        "entry": [
          -417.885,
          65.651,
          -240.985
        ],
        "yaw": -1.715
      },
      {
        "model": "wedge",
        "entry": [
          -431.912,
          63.777,
          -227.861
        ],
        "yaw": -1.715
      },
      {
        "model": "wedge",
        "entry": [
          -455.426,
          64.153,
          -231.268
        ],
        "yaw": 1.427
      },
      {
        "model": "curve",
        "entry": [
          -437.018,
          62.364,
          -220.517
        ],
        "yaw": -1.715
      }
    ],
    "sign": {
      "position": [
        -409.135,
        65.045,
        -231.633
      ],
      "yaw": 1.427
    },
    "start": {
      "position": [
        -396.112,
        66.098,
        -237.83
      ],
      "headingRad": -1.427
    },
    "clear": [
      {
        "x": -442.784,
        "z": -236.509,
        "radius": 46
      }
    ]
  }
];
