// Generated by scripts/generate-stunt-sites.ts. Do not edit by hand; re-run `npm run generate:stunts`.
import type { StuntSite } from './stuntSites';

export const STUNT_SITES: StuntSite[] = [
  {
    "id": "river-jump-malakkappara-river-2-22",
    "label": "Chalakkudy River Jump",
    "kind": "river",
    "ramps": [
      {
        "model": "wedge",
        "entry": [
          -684.43,
          79.874,
          -654.856
        ],
        "yaw": 1.759
      },
      {
        "model": "wedge",
        "entry": [
          -647.337,
          79.881,
          -661.921
        ],
        "yaw": -1.383
      }
    ],
    "sign": {
      "position": [
        -691.353,
        76.792,
        -648.447
      ],
      "yaw": -1.383
    },
    "start": {
      "position": [
        -711.936,
        74.823,
        -649.617
      ],
      "headingRad": 1.383
    },
    "clear": [
      {
        "x": -684.43,
        "z": -654.856,
        "radius": 10
      },
      {
        "x": -647.337,
        "z": -661.921,
        "radius": 10
      },
      {
        "x": -679.636,
        "z": -655.769,
        "radius": 10
      },
      {
        "x": -652.131,
        "z": -661.008,
        "radius": 10
      },
      {
        "x": -699.165,
        "z": -652.049,
        "radius": 10
      },
      {
        "x": -632.602,
        "z": -664.728,
        "radius": 10
      }
    ]
  },
  {
    "id": "river-jump-malakkappara-river-3-46",
    "label": "Chalakkudy River Jump II",
    "kind": "river",
    "ramps": [
      {
        "model": "wedge",
        "entry": [
          -661.444,
          74.466,
          -526.611
        ],
        "yaw": 1.728
      },
      {
        "model": "wedge",
        "entry": [
          -624.15,
          74.422,
          -532.524
        ],
        "yaw": -1.414
      }
    ],
    "sign": {
      "position": [
        -668.563,
        76.097,
        -520.42
      ],
      "yaw": -1.414
    },
    "start": {
      "position": [
        -689.099,
        75.776,
        -522.227
      ],
      "headingRad": 1.414
    },
    "clear": [
      {
        "x": -661.444,
        "z": -526.611,
        "radius": 10
      },
      {
        "x": -624.15,
        "z": -532.524,
        "radius": 10
      },
      {
        "x": -656.625,
        "z": -527.375,
        "radius": 10
      },
      {
        "x": -628.97,
        "z": -531.76,
        "radius": 10
      },
      {
        "x": -676.259,
        "z": -524.262,
        "radius": 10
      },
      {
        "x": -609.335,
        "z": -534.872,
        "radius": 10
      }
    ]
  },
  {
    "id": "stunt-park-chokkana-1",
    "label": "Chokkana Stunt Park",
    "kind": "park",
    "ramps": [
      {
        "model": "kicker",
        "entry": [
          -270.312,
          66.917,
          -342.949
        ],
        "yaw": 1.522
      },
      {
        "model": "wedge",
        "entry": [
          -257.598,
          66.565,
          -357.348
        ],
        "yaw": 1.522
      },
      {
        "model": "wedge",
        "entry": [
          -233.866,
          66.254,
          -356.195
        ],
        "yaw": -1.619
      },
      {
        "model": "curve",
        "entry": [
          -253.215,
          66.354,
          -365.145
        ],
        "yaw": 1.522
      }
    ],
    "sign": {
      "position": [
        -279.912,
        66.681,
        -351.425
      ],
      "yaw": -1.619
    },
    "start": {
      "position": [
        -292.286,
        66.64,
        -344.017
      ],
      "headingRad": 1.619
    },
    "clear": [
      {
        "x": -245.952,
        "z": -349.774,
        "radius": 46
      }
    ]
  },
  {
    "id": "stunt-park-kodassery-1",
    "label": "Kodassery Stunt Park",
    "kind": "park",
    "ramps": [
      {
        "model": "kicker",
        "entry": [
          -419.345,
          61.163,
          -680.201
        ],
        "yaw": -2.643
      },
      {
        "model": "wedge",
        "entry": [
          -438.259,
          60.847,
          -683.558
        ],
        "yaw": -2.643
      },
      {
        "model": "wedge",
        "entry": [
          -449.631,
          61.199,
          -704.419
        ],
        "yaw": 0.499
      },
      {
        "model": "curve",
        "entry": [
          -447.198,
          60.822,
          -683.241
        ],
        "yaw": -2.643
      }
    ],
    "sign": {
      "position": [
        -421.583,
        61.263,
        -667.592
      ],
      "yaw": 0.499
    },
    "start": {
      "position": [
        -408.816,
        61.927,
        -660.884
      ],
      "headingRad": -0.499
    },
    "clear": [
      {
        "x": -437.856,
        "z": -697.444,
        "radius": 46
      }
    ]
  },
  {
    "id": "stunt-park-kadambode-1",
    "label": "Kadambode Stunt Park",
    "kind": "park",
    "ramps": [
      {
        "model": "kicker",
        "entry": [
          -690.833,
          49.567,
          -267.651
        ],
        "yaw": 3.003
      },
      {
        "model": "wedge",
        "entry": [
          -704.027,
          49.057,
          -281.612
        ],
        "yaw": 3.003
      },
      {
        "model": "wedge",
        "entry": [
          -700.738,
          49.18,
          -305.143
        ],
        "yaw": -0.139
      },
      {
        "model": "curve",
        "entry": [
          -711.396,
          48.721,
          -286.681
        ],
        "yaw": 3.003
      }
    ],
    "sign": {
      "position": [
        -700.14,
        49.424,
        -258.855
      ],
      "yaw": -0.139
    },
    "start": {
      "position": [
        -693.879,
        52.185,
        -245.863
      ],
      "headingRad": 0.139
    },
    "clear": [
      {
        "x": -695.433,
        "z": -292.528,
        "radius": 46
      }
    ]
  },
  {
    "id": "stunt-park-kodaly-1",
    "label": "Kodaly Stunt Park",
    "kind": "park",
    "ramps": [
      {
        "model": "kicker",
        "entry": [
          -50.414,
          8.776,
          30.86
        ],
        "yaw": 3.063
      },
      {
        "model": "wedge",
        "entry": [
          -64.43,
          9.463,
          17.724
        ],
        "yaw": 3.063
      },
      {
        "model": "wedge",
        "entry": [
          -62.572,
          10.425,
          -5.964
        ],
        "yaw": -0.078
      },
      {
        "model": "curve",
        "entry": [
          -72.093,
          9.733,
          13.11
        ],
        "yaw": 3.063
      }
    ],
    "sign": {
      "position": [
        -59.171,
        8.362,
        40.204
      ],
      "yaw": -0.078
    },
    "start": {
      "position": [
        -52.134,
        7.711,
        52.792
      ],
      "headingRad": 0.078
    },
    "clear": [
      {
        "x": -56.513,
        "z": 6.308,
        "radius": 46
      }
    ]
  },
  {
    "id": "stunt-park-kodaly-2",
    "label": "Kodaly Stunt Park II",
    "kind": "park",
    "ramps": [
      {
        "model": "kicker",
        "entry": [
          -456.937,
          28.203,
          58.472
        ],
        "yaw": -1.69
      },
      {
        "model": "wedge",
        "entry": [
          -470.629,
          26.536,
          71.945
        ],
        "yaw": -1.69
      },
      {
        "model": "wedge",
        "entry": [
          -494.222,
          26.503,
          69.13
        ],
        "yaw": 1.452
      },
      {
        "model": "curve",
        "entry": [
          -475.548,
          25.638,
          79.415
        ],
        "yaw": -1.69
      }
    ],
    "sign": {
      "position": [
        -447.955,
        27.67,
        67.6
      ],
      "yaw": 1.452
    },
    "start": {
      "position": [
        -435.092,
        28.581,
        61.077
      ],
      "headingRad": -1.452
    },
    "clear": [
      {
        "x": -481.715,
        "z": 63.573,
        "radius": 46
      }
    ]
  },
  {
    "id": "stunt-park-chokkana-2",
    "label": "Chokkana Stunt Park II",
    "kind": "park",
    "ramps": [
      {
        "model": "kicker",
        "entry": [
          -435.318,
          65.686,
          -255.124
        ],
        "yaw": -1.728
      },
      {
        "model": "wedge",
        "entry": [
          -449.518,
          65.722,
          -242.188
        ],
        "yaw": -1.728
      },
      {
        "model": "wedge",
        "entry": [
          -472.986,
          66.148,
          -245.907
        ],
        "yaw": 1.414
      },
      {
        "model": "curve",
        "entry": [
          -454.721,
          64.967,
          -234.912
        ],
        "yaw": -1.728
      }
    ],
    "sign": {
      "position": [
        -426.694,
        66.092,
        -245.658
      ],
      "yaw": 1.414
    },
    "start": {
      "position": [
        -413.59,
        66.269,
        -251.681
      ],
      "headingRad": -1.414
    },
    "clear": [
      {
        "x": -460.275,
        "z": -250.98,
        "radius": 46
      }
    ]
  },
  {
    "id": "stunt-park-kodassery-2",
    "label": "Kodassery Stunt Park II",
    "kind": "park",
    "ramps": [
      {
        "model": "kicker",
        "entry": [
          33.023,
          75.789,
          -559.61
        ],
        "yaw": 2.031
      },
      {
        "model": "wedge",
        "entry": [
          37.108,
          77.332,
          -578.38
        ],
        "yaw": 2.031
      },
      {
        "model": "wedge",
        "entry": [
          58.393,
          75.775,
          -588.938
        ],
        "yaw": -1.11
      },
      {
        "model": "curve",
        "entry": [
          37.136,
          77.601,
          -587.324
        ],
        "yaw": 2.031
      }
    ],
    "sign": {
      "position": [
        20.51,
        78.384,
        -562.333
      ],
      "yaw": -1.11
    },
    "start": {
      "position": [
        13.315,
        77.491,
        -549.834
      ],
      "headingRad": 1.11
    },
    "clear": [
      {
        "x": 50.969,
        "z": -577.441,
        "radius": 46
      }
    ]
  }
];
