/**
 * Searches the world for stunt parks and river jumps and writes the result to
 * src/game/world/stuntSites.data.ts. Re-run after changing terrain, roads or buildings:
 *   npm run generate:stunts
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { findParks, findRiverJumps } from '../src/game/world/stuntSites';

const round = (value: unknown): unknown =>
  typeof value === 'number' ? Math.round(value * 1000) / 1000 : Array.isArray(value) ? value.map(round)
    : value && typeof value === 'object' ? Object.fromEntries(Object.entries(value).map(([k, v]) => [k, round(v)])) : value;

const rivers = findRiverJumps();
const parks = findParks(rivers.flatMap(site => site.clear.map(c => [c.x, c.z] as [number, number])));
const sites = round([...rivers, ...parks]);
const out = fileURLToPath(new URL('../src/game/world/stuntSites.data.ts', import.meta.url));
writeFileSync(out, `// Generated by scripts/generate-stunt-sites.ts. Do not edit by hand; re-run \`npm run generate:stunts\`.\nimport type { StuntSite } from './stuntSites';\n\nexport const STUNT_SITES: StuntSite[] = ${JSON.stringify(sites, null, 2)};\n`);
console.log(`Wrote ${rivers.length} river jumps and ${parks.length} parks to ${out}`);
